name: GunsPlugin
version: '${project.version}'
main: com.andrew.guns.Main
api-version: 1.20
authors: [ Andrew ]
description: 5 different gun that do 5 different things
commands:
  launchermenu:
    aliases: lm
    description: A GUI for all launchers
  launcher:
    aliases: l
    description: A command to spawn a launcher
